### ISSUE TITLE
Cài đặt Sql server 2012 express lên 14.140

### ISSUE THREAD

**Issue by baotnq** [vinaas/medihub-website#1]
- Cài đặt sql server
- Thiết lập để có thể kết nối từ bên ngoài qua SQL Studio ...

**Comment by thinnv** [comment]
- Đã cài xong và public port 1433
- Thông tin connect :
   Ip 104.140.14.140
  user : sa
  pass: Vinaas!@#456
  Tạm thời sài user sa, cần thiết sẽ tạo 1 user thay thế
